### ISSUE TITLE
Roadmap - Version 0.4

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#172]
# New features
- [x] Corrupted items are now colored red - #53 #74
- [x] Sets the min item level to 86 if the item level is above 86 - #15 #77
- [x] Added price prediction on rare items from poeprices.info - #79 #130
- [x] Added configurable settings - #7 #83 #94 #131 #132 #167 #170 #175 #176 
  - [x] Option to choose the desired wiki between poedb and poe wiki - #96 #101
  - [x] Added a setting to retain the clipboard data - #143 
- [x] Opening the item wiki can be opened for any items - #119
- [x] Added support for garena taiwan version - #99
- [x] Leave party command is now implemented - #100 #116
- [x] Find items command is now implemented - #87 #100
- [x] Implemented infinite scroll feature to the overlay - #9 #102
- [x] Sidekick now detects if it requires admin privilege and prompts the user if it does. - #69 #93 #105
- [x] Added a hotkey to open the search on the web browser - #103 #107
- [x] Added support for multiple UI language - #40 #108 #177 
- [x] Added support for poe.ninja - #5 #137
- [x] Added an auto updater - #11 #147 
  - [x] After the last few Pull requests, this needs retesting.
- [x] Added cheatsheets - #122 #174 
  - [x] Betrayal - #149 
  - [x] Incursion - #155 
  - [x] Blight - #158 
  - [x] Delve - #162 
  - [x] Metamorph - #158 
- [x] Added support for Metamorph samples - #127 #151 
- [x] Show item stats on mouse hover - #129 #160 
- [x] Added a splashscreen - #161 

# Bug fixes
- [x] Fixed the mouse lag issue when closing Sidekick - #30 #89
- [x] Items in chat are now correctly parsed - #82 #112 
- [x] Divination card stash tab is no longer buggy - #84
- [x] Unique maps show valid results - #138 #150 

# Code and performance enhancements
- [x] Use only one instance of HttpClient throughout the app - #86 #98 #115 #123
- [x] Refactored the solution into multiple projects to clearly define boundaries in the code. It should help with maintainability and stability in the long run. - #97 #104 #118 #121 #123 #145 #148 #154 #159 #168 
- [x] Implemented the Dependency Injection pattern. - #97 #110
- [x] Improved the app initialization process - #113 #124
  - [x] Move the report progress for the splash screen to the initializer class - #166 
- [x] Removed dependency on Newtonsoft.Json - #111 #123 #136 #167 
- [x] Refactored the code about the tray icon - #139
- [x] Implement resource files as a replacement for the UILanguageProvider - #157
  - [x] Settings
  - [x] League overlay
  - [x] Tray icon
  - [x] Main overlay
- [x] Rename the Sidekick project to Sidekick.UI.Windows - #169 

# Remaining
### Bugs / Improvements
- [x] Validate that Ctrl+D happens with no issue. Currently there are reports that it works only half of the time
- [x] Pressing space also closes the stash and inventory in the game
- [x] Make sure the performance is optimal regarding the Ctrl+Scroll to swap stash tabs
- [x] Validate that the Overlay is opened before trying to close it
- [x] Fix keybind settings
- [x] Fix opening the league overlay
- [x] Style the Character name textbox in the settings
- [x] Rename some setting properties
- [x] Can unbind setting
- [x] If autoupdate fails, we need to open the browser to the releases page
