### ISSUE TITLE
Roadmap - Version 0.5

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#191]
# Features
- [x] Global style review.
  - There was a lot of styles put into the Styles.xaml. We need to do more. There are a lot of controls that are overriding the default styles. We need to use the default styles (from styles.xaml) most of the time.
- [x] Better feedback when price checking items. We need to show the overlay first, and then try to get the prices. #141 
  - We also need to provide feedback when price checking fails.
- [x] Implement icons for currency. #50 

# Optimization
- [x] Move to .Net Core 3
  - Single executable
- [x] Split the League overlay into multiple user control or windows for easier maintenance
- [x] Implement resources for all strings that are visible in the overlays
- [x] Implement view models for all views

**Comment by cmos12345** [comment]
What do you guys think about implementing unit-tests when version 0.4.0 is released?

**Comment by Zalhera** [comment]
@leMicin Can you include the advanced search feature to the features list of this Version?

**Comment by leMicin** [comment]
Done :)

**Comment by Blinke** [comment]
#63 is part of the 0.6 milestone rather than this one, should probably be removed from this list?

**Comment by leMicin** [comment]
Done.

Yeah we made this list before we started 0.5.0. Priorities change and we didn't keep this updated. We will generate the changelog from the Milestone rather than this list anyway.

We are planning a release with the new league later this week.

**Comment by bgriffs** [comment]
Is the hope to have advanced searched ready for 3.10 launch?

**Comment by leMicin** [comment]
It is the hope.... Either way we are making a release before the launch. If advanced search is not there for 3.10, we will release it as soon as it is ready.

**Comment by Zalhera** [comment]
The core for advanced search is ready, but there are some things that need adjustment.
Unfortunately I don't think that I'm able to finish everything before the launch.

**Comment by leMicin** [comment]
@Zalhera I am planning on working on it all day friday, to try and make it ready for launch.

Before friday, I will work on the smaller remaining issues.
