### ISSUE TITLE
Roadmap - Version 0.7.0

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#291]
# Introduction
Filters were released in version 0.6.0. There are still a lot of features missing from the filters that needs to be implemented. This is where this version will handle all the missing cases from the filters.

We released 0.6.0 as soon as we could because a lot of people were asking for filters. Even though a lot of features are missing we thought it was a good idea to release a part of the filters in 0.6.0.

# Enhancements for 0.7.0
- [x] Add property filters #289 
- [x] Add pseudo modifiers filters #288 
- [x] Remember active filters between uses #287

**Comment by Newbrict** [comment]
You said released but there is no new release? Is it a build it yourself only release or something?

**Comment by leMicin** [comment]
It is coming in the next few minutes!
