### ISSUE TITLE
[Map] Better user experience in the settings

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#390]
# Summary
@PeteyPii Did an amazing job getting this feature started with #389 . We wanted the feature for version 1.0, but we want to make it better in a future version. If you want to do the adjustments yourself, just reply here and we will assign it to you :) .

# Goals
Add a tab in the settings for the map info view. Inside that tab, there would be a list of checkboxes with different pre-determined list of dangerous mods. If the checkbox is active, then we check if that mod is found on the map. The regex would be located in the LanguageProvider object so that they can be translated. This will be cleaner for the end user, instead of asking them to manipulate a regex.

# Tasks
- [ ] Add a tab in the settings view for Map Info settings.
- [ ] Show checkboxes for each dangerous mod.
- [ ] Save the state of the checkboxes in the settings. By default, all dangerous mod should be checked.
- [ ] Determine if a user-selected dangerous mod is listed in the map.
- [ ] Use and store language-specific regex in the Language Provider. For languages that we do not have the translation, use '\_\_TranslationRequired\_\_'.

**Comment by leMicin** [comment]
Moved to https://github.com/Sidekick-Poe/Sidekick/issues/5
