### ISSUE TITLE
Rethink the initialization process of Sidekick

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#432]
We have hit a major problem with #431 . I am rethinking the way we initialize the app.

Some foreign clients are being flagged by CloudFlare, we cannot assume a client will be able to communicate with any API (Korean => English). We are assuming the client can communicate with their local region API (Korean => Korean).  So before we make any calls, we need to know which client to call.

# First run
On a first run, we will ask for the user's game language. The game language will become a setting and will no longer be auto detected based on the game because of this. On a first run, because we will require user information, we can also ask some initial settings such as Character name.

# Subsequent runs
Should be mostly unchanged from a user experience perspective. When we detect that leagues have changed, we should show the first run form again so the user can select the league.

# Pseudo mods
The English API is required to parse pseudo modifiers. If the English API is unable to be contacted, we need to be able to not crash the application in this case. Pseudo mods should be able to be gracefully degraded.

# Tasks
- [x] Rename the SplashScreenView to InitializeView.
- [x] Move all the initialization logic inside the InitializeViewModel.
- [x] Depending on the settings, do not show the InitializeView unless required by scenarios below.
- [x] Remove the auto language detection feature.
- [x] Add a game language setting
- [x] When the language setting changes, re-initialize the app
- [x] When parsing fails, suggest to the user that the language may be set incorrectly
- [x] Detect when it is a user's first run
  - [x] Ask for game language
  - [x] Ask for character name (optional)
- [x] Detect when league changes
  - [x] Ask for game language
  - [x] Ask for character name (optional)
