### ISSUE TITLE
[Chat] All chat commands should be custom chat commands

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#527]
@JadedCricket did a great job implementing custom chat commands in #494 .

I would like to expand on that by using the custom commands for all chat commands. The default settings would include the currently setup chat commands, but a user could remove those commands. This allows greater flexibility and easier maintenance for us.

# Tasks
- [x] Default settings should include current functionality
  - [x] Go to hideout
  - [x] Reply to last whisper
  - [x] Leave party
  - [x] Exit to character screen
- [x] Add wildcards for chat commands
  - [x] {Me.CharacterName} for your own character name
  - [x] {LastWhisper.CharacterName} for the character name of the last whisper your received
- [x] Add chat option to send the command, or only start writing without sending it
- [x] Add documentation in the UI
  - [x] Popular commands (hideout, exit)
  - [x] Wildcards
